### ISSUE TITLE
btsync-core crashed with SIGFPE in __udivdi3()

### ISSUE THREAD

**Issue by kodybaker** [Silvenga/btsync-deb#1]
Hi there,

I was running 2.2.5 fine for the past little while, but then over the weekend it appears that btsync had crashed. Now, when rebooting the machine and restarting btsync, I get an immediate crash.

Here's the info from the error report:
Path:
/usr/lib/btsync-core/btsync-core
Package:
btsync-core 2.2.5-1.0 [origin: btsync any]
ProblemType
Crash
Title
btsync-core crashed with SIGFPE in __udivdi3()
ApportVersion:
2.14.1-0ubuntu3.18
Arch:
i386

I think that's the key stuff. 

Let me know if I can add any more details.

**Comment by kodybaker** [comment]
Strange though... 
It appears btsync is still functioning.

**Comment by Silvenga** [comment]
Hmmm... SIGFPE is generally a number error so there isn't much we can discern without the source code. 

As the btsync-deb project provides only a wrapper for the official Btsync binary, this particular crash might find better help directly from Bittorrent or on their forums.

**Comment by ndmax** [comment]
Verifying Packages w/ apt-key:

```
gpg: requesting key 3C3DE741 from hkp server keyserver.ubuntu.com
gpg: no writable keyring found: eof
gpg: error reading `[stream]': general error
```

Updating w/ apt-get update after adding repository:

```
GPG error: http://deb.silvenga.com any InRelease: The following signatures couldn't be verified
because the public key is not available: NO_PUBKEY 992A3C9A3C3DE741
```

**Comment by Silvenga** [comment]
@ndmax did you run `apt-key` under root?

**Comment by ndmax** [comment]
@Silvenga I feel so silly...

**Comment by Silvenga** [comment]
@ndmax Not a problem! :smile: 

@kodybaker I'm going to close this ticket for now - any other problems please feel free to open another issue.
