### ISSUE TITLE
Upgrade process hangs

### ISSUE THREAD

**Issue by filemoon** [Silvenga/btsync-deb#10]
I have 4 arm "servers" they all are hangs 

"The following packages will be upgraded:
  btsync-core
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4,441 kB of archives.
After this operation, 6,144 B disk space will be freed.
Do you want to continue? [Y/n] y
Reading changelogs... Done
(Reading database ... 25660 files and directories currently installed.)
Preparing to unpack .../btsync-core_2.3.6-1.0_armhf.deb ...
Unpacking btsync-core (2.3.6-1.0) over (2.3.3-1.0) ...
Processing triggers for btsync (2.3.0-1.0) ..."

When I cancel this and restart server "dpkg --configure -a" did not solve the issue,
Setting up btsync-core (2.3.6-1.0) ...
Setting up btsync (2.3.0-1.0) ...

**Comment by Silvenga** [comment]
Can you try to remove `btsync-core` and reinstall it (configuration will be preserved)?

**Comment by filemoon** [comment]
apt-get install btsync
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  btsync-core
Suggested packages:
  bind-shim
The following NEW packages will be installed:
  btsync btsync-core
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 101 kB/4,542 kB of archives.
After this operation, 8,726 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.silvenga.com/btsync/ any/main btsync all 2.3.0-1.0 [101 kB]
Fetched 101 kB in 1s (83.1 kB/s) 
Preconfiguring packages ...

not working.

Regards Chris

**Comment by filemoon** [comment]
I’ve aslo tested general fix procedure:
“
sudo apt-get update

sudo apt-get clean

sudo apt-get autoremove

sudo apt-get update && sudo apt-get upgrade

sudo dpkg --configure -a

sudo apt-get install -f
“

no luck too.

I see this package is recomended -
Suggested packages:
  bind-shim

but i have no installation candidate

regards Chris

**Comment by filemoon** [comment]
was able to install it again after /var/cache/debconf/config.dat file was deleted too.
Right now is working ok on all 4 servers.

**Comment by Silvenga** [comment]
That's interesting @filemoon - what made you try that?

**Comment by Silvenga** [comment]
As I haven't received any additional reports of this issue, I'm going to consider this an isolated event. If this happens again please feel free to reopen this ticket.
