### ISSUE TITLE
Update btsync-gui to btsync version 2.x?

### ISSUE THREAD

**Issue by AlbrechtL** [Silvenga/btsync-deb#12]
Hi,
Thanks for providing this repository. Thus, btsync-gui runs perfectly with Ubuntu 16.04.1.
Are they any chances to update the btsync-gui to a newer btsync version?

Bye, Al

**Comment by Silvenga** [comment]
If I remember correctly, Bittorrent requires extra payment for API access to btsync. I'm not sure if it would be possible anymore - even the key generation location that tuxpoldo used doesn't exist anymore. :disappointed: 

https://getsync.com/api
