### ISSUE TITLE
Start failed after 2.5 upgrade

### ISSUE THREAD

**Issue by LorMugnaini** [Silvenga/btsync-deb#13]
After upgrading btsync-core from 2.4.5-1.0 to 2.5-1.0 the daemon cannot start anymore:
Failed to start btsync instance debconf-default - please check the configuration file /etc/btsync/debconf-default.conf

Ubuntu Server 14.04 on Atom CPU.

Downgrading to 2.4.5-1.0 temporarly solved the issue

**Comment by Silvenga** [comment]
Can you see if there's a log for that error in `/tmp/`. I'll look further into this when I get home tonight. Ping me if I forget. 😸

**Comment by Silvenga** [comment]
@LorMugnaini fixed in btsync `2.5.0-1.0`.
