### ISSUE TITLE
Package signing key expired

### ISSUE THREAD

**Issue by viceice** [Silvenga/btsync-deb#14]
Hi

the deb signing key seems to be expired:

Err:4 http://deb.silvenga.com/btsync any InRelease
The following signatures were invalid: KEYEXPIRED 1500219473  KEYEXPIRED 1500223169  KEYEXPIRED 1500223169  KEYEXPIRED 1500219473  KEYEXPIRED 1500223169  KEYEXPIRED 1500219473  KEYEXPIRED 1500223169

Regards
Michael

**Comment by Silvenga** [comment]
Thanks for the report @ViceIce! Yes, my key did expire a couple week ago. I've pushed the update around that time to `keyserver.ubuntu.com` (someone else contacted me by email). 

Please run the key import again to update your local copy of my keys:

```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 37F1A037FEF78709
```

**Comment by viceice** [comment]
@Silvenga Works! Thanks. 👍
