### ISSUE TITLE
Latest Sync versions missing

### ISSUE THREAD

**Issue by marcel-sch** [Silvenga/btsync-deb#18]
Hello,

your repo is still at 2.6.3 but 2.7.2 is available. Please have a look.

Thank you.

**Comment by Silvenga** [comment]
Yep, they changed the URL I was scraping for updates. Feel free to poke me if I forgot, I'll likely have time this weekend.

**Comment by marcel-sch** [comment]
poke ;-)

**Comment by Silvenga** [comment]
Freak, sorry. Thanks for the poke.

**Comment by Silvenga** [comment]
My private instance of Jenkins decided to die sometime in the past week. Might be a good opportunity to move this repo to Github actions... been meaning to get rid of Jenkins.

**Comment by Silvenga** [comment]
Should be good now, let me know if it isn't.
