### ISSUE TITLE
 Package signing key expired (again)

### ISSUE THREAD

**Issue by emagra** [Silvenga/btsync-deb#20]
Hi

the deb signing key seems to be expired:

Err:4 http://deb.silvenga.com/btsync any InRelease
EXPKEYSIG 53D9A164332997D8 Mark Lopez (Authority) <m@silvenga.com>

Cheers!

**Comment by Silvenga** [comment]
Whoa, 3 years flies by - this time I swear I have a calendar entry to remind myself. Bad gpg key maintenance on my part. 

Keys renewed and published to keyservers: https://keyserver.ubuntu.com/pks/lookup?search=0xdc7580d80d6753dcf2092a5437f1a037fef78709&fingerprint=on&op=index

Thanks for sticking with me over all these years. 🥰
