### ISSUE TITLE
dpkg not offering user/pass

### ISSUE THREAD

**Issue by jhoogeboom** [Silvenga/btsync-deb#4]
trying to follow this [guide](https://www.digitalocean.com/community/tutorials/how-to-use-bittorrent-sync-to-synchronize-directories-in-ubuntu-14-04) but

``` bash
sudo dpkg-reconfigure btsync
```

never asks me to fill in a user and pass for the web interface, although on connecting it does ask for a user and pass, it doesn't seem to be able to log out again.

**Comment by Silvenga** [comment]
> never asks me to fill in a user and pass for the web interface

@jhoogeboom the guide referenced above is describing Btsync 1.3, hence it may not be relevant to the current version of 2.0. 

For example, in version 2.0 you don't need a reverse proxy like Nginx for SSL termination as it's now a built-in feature. Additionally, folder structure is created for you. 

I would simply follow the sets outlined on the front page of this repository and nothing more. 

> it doesn't seem to be able to log out again.

If I understand correctly - you want to make sure that the instance is password protected and closing the page and opening it again doesn't prompt for a password. 

The browser caches your login information. Restarting your browser will effectively log you out.

**Comment by jhoogeboom** [comment]
Thank you, I didn't know it was describing a  previous version, makes more sense now.
