### ISSUE TITLE
Make Log-file path and name adjustable

### ISSUE THREAD

**Issue by 17Halbe** [Silvenga/btsync-deb#6]
Hi there, 

it would be nice to have an option to make the Logfile directory adjustable. It is currently hardcoded under /temp/sync.log. 
Following Problems:
Default-Config File(/etc/btsync/) does not support a Log-Setting.

Possible Solution:
adjust the setting DAEMON_ARGS="" in /etc/default/btsync.

This is my first action in Github at all. So I could also provide a pull request on this one.. Don't really know my way around here yet.. So please be patient on me!! ;)

**Comment by Silvenga** [comment]
Yeah, I always hated that. It would be cool if there was a setting in `dpkg-reconfigure btsync` to configure the log path. 

With a quick look I think this would be promising:

https://github.com/Silvenga/btsync-deb/blob/master/btsync/debian/btsync.init.d#L160 

I'll look more into this latter today. I'm always open to pull requests if you want. :) 

> This is my first action in Github at all.

That is awesome! :+1:

**Comment by 17Halbe** [comment]
Yeah, configuring via `dpkg-reconfigure` would be great. I don't know how to code this though. 

Problem with your link and the `config_from_conffile` function is, that it's evaluating the /etc/btsync.conf and the provided default config file from Bittorrent Sync (the output of `btsync-daemon --dump-sample-config`) doesn't provide a log file option. 
So since it isn't a default option in the .conf file, I would rather support placing it in the `/etc/default/btsync` file under `DAEMON_ARGS`

**Comment by Silvenga** [comment]
@17Halbe first off, thanks for the pull request. 

However, I think I got it working using reconfigure - what Tuxpoldo did was to use comments to store non-standard configurations in `/etc/btsync.conf`. Then using Regex he pulled the values during init. I used a similar method. 

Could you try and upgrade to `btsync` 2.3.0-1.0? The setting is in `dpkg-reconfigure`'s advanced settings.

**Comment by 17Halbe** [comment]
As long as it works it would be fine for me anyway! ;)

I just hesitated adding anything to the .conf file which isn't supported from the `-dump-sample-config`.
So if someone uses the default config file provided by Bittorrent Sync, he would just log to `/temp/sync.log` and he wouldn't know, that there would be this hidden setting in the conf file. 
I do see this as a remote occasion though. 
I'll be upgrading in a second. Thanks für your work!
edit: Just to make it clear: No objections from my side! ;)
