### ISSUE TITLE
Latest Sync versions missing

### ISSUE THREAD

**Issue by imyller** [Silvenga/btsync-deb#8]
From README:

> New versions should be automatically built and published to this location via my build server (found above) when new changelogs are released.

This doesn't seem to work right now. deb.silvenga.com `btsync` packages are left in version `2.3.3` missing at least following versions:
- `2.3.4`
- `2.3.5`
- `2.3.6`

**Comment by Silvenga** [comment]
I just saw this some five minutes ago too. It looks like Bittorrent updated their changelog page (I have to parse the HTML). I'll update them manually in a little while.

**Comment by Silvenga** [comment]
Thanks for the tip - I've pushed the update to my repositories. Always feel free to open an issue if my server is delayed.

**Comment by imyller** [comment]
Thank you for your quick response.
